// Copyright Yamahasxviper. All Rights Reserved.
// Direct port of Tools/BanSystem/src/index.ts

#include "BanSystemModule.h"
#include "BanDatabase.h"
#include "BanSystemConfig.h"
#include "HAL/PlatformFileManager.h"
#include "Misc/ConfigCacheIni.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"

DEFINE_LOG_CATEGORY_STATIC(LogBanSystem, Log, All);

#define LOCTEXT_NAMESPACE "FBanSystemModule"

void FBanSystemModule::StartupModule()
{
    UE_LOG(LogBanSystem, Log, TEXT("BanSystem module starting."));
    // UBanDatabase, UBanRestApi, and UBanEnforcer are UGameInstanceSubsystem
    // subclasses and initialise automatically when the game instance starts.
    // No manual setup is required here.

    // On the very first startup after the operator has configured settings,
    // write a backup to Saved/Config/<Platform>/BanSystem.ini.  UE reads that
    // file with higher priority than the mod's Config/DefaultBanSystem.ini, so
    // settings survive an Alpakit dev deploy that deletes the mod directory.
    BackupConfigIfNeeded();

    UE_LOG(LogBanSystem, Log, TEXT("BanSystem module started."));
}

void FBanSystemModule::BackupConfigIfNeeded()
{
    const UBanSystemConfig* Cfg = UBanSystemConfig::Get();
    if (!Cfg) return;

    // Only write when the operator has changed at least one value from its
    // compiled-in default; there is nothing useful to back up otherwise.
    const bool bHasCustomSettings =
        !Cfg->DatabasePath.IsEmpty() ||
        Cfg->RestApiPort != 3000     ||
        Cfg->MaxBackups  != 5;

    if (!bHasCustomSettings)
    {
        UE_LOG(LogBanSystem, Log, TEXT("BanSystem: Config has default values – no backup needed."));
        return;
    }

    // Resolved at runtime: Saved/Config/<Platform>/BanSystem.ini
    // e.g. Saved/Config/WindowsServer/BanSystem.ini  or  Saved/Config/LinuxServer/BanSystem.ini
    const FString BackupPath = FPaths::Combine(
        FPaths::ProjectSavedDir(),
        TEXT("Config"),
        FString(FPlatformProperties::PlatformName()),
        TEXT("BanSystem.ini"));

    IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();

    // Only write on first run.  If the file already exists the operator is
    // managing it directly and we must not overwrite their customisations.
    if (PlatformFile.FileExists(*BackupPath))
    {
        UE_LOG(LogBanSystem, Log,
            TEXT("BanSystem: Backup config already exists at '%s' – skipping."), *BackupPath);
        return;
    }

    // Build the INI content.  Use string concatenation (not Printf) to avoid
    // misinterpreting any '%' characters that might appear in a custom DatabasePath.
    const FString Content =
        FString(TEXT("; Auto-generated by BanSystem on first startup.\n"))
        + TEXT("; Preserves settings across mod updates and Alpakit dev deploys.\n")
        + TEXT("; Edit this file instead of Mods/BanSystem/Config/DefaultBanSystem.ini\n")
        + TEXT("; (that file may be overwritten when the mod is updated).\n")
        + TEXT("\n")
        + TEXT("[/Script/BanSystem.BanSystemConfig]\n")
        + TEXT("DatabasePath=") + Cfg->DatabasePath + TEXT("\n")
        + TEXT("RestApiPort=")  + FString::FromInt(Cfg->RestApiPort) + TEXT("\n")
        + TEXT("MaxBackups=")   + FString::FromInt(Cfg->MaxBackups)  + TEXT("\n");

    PlatformFile.CreateDirectoryTree(*FPaths::GetPath(BackupPath));

    if (FFileHelper::SaveStringToFile(Content, *BackupPath))
    {
        UE_LOG(LogBanSystem, Log,
            TEXT("BanSystem: Wrote backup config to '%s'. Settings will now survive mod updates."),
            *BackupPath);
    }
    else
    {
        UE_LOG(LogBanSystem, Warning,
            TEXT("BanSystem: Could not write backup config to '%s'."), *BackupPath);
    }
}

void FBanSystemModule::ShutdownModule()
{
    UE_LOG(LogBanSystem, Log, TEXT("BanSystem module shut down."));
}

#undef LOCTEXT_NAMESPACE

IMPLEMENT_MODULE(FBanSystemModule, BanSystem)
